[[libknet8]]
arch = "x86_64"
git-tree-sha1 = "172aab1c490da4e9f26ed08c3b8e99cd86e8d7e7"
os = "linux"

   [[libknet8.download]]
   sha256 = "84a33826b8dd45451852be25bdc84a070f9bc418b09ab093cce5682abb54377a"
   url = "https://github.com/denizyuret/Knet.jl/releases/download/v1.4.0/libknet8.x86_64-linux-gnu.tar.gz"

[[libknet8]]
arch = "x86_64"
git-tree-sha1 = "9f36b4ee16e483534b1031bc272c9f4cb8443088"
os = "windows"

   [[libknet8.download]]
   sha256 = "04175385bb0c06a4efccd4a09b5c66fc832097b15a5e0316647d4c66a1cc2b7e"
   url = "https://github.com/denizyuret/Knet.jl/releases/download/v1.3.8/libknet8.x86_64-windows.tar.gz"

[[libknet8]]
arch = "x86_64"
git-tree-sha1 = "de5d5055f7f4258582ca67420d9dbcc944e65b50"
os = "macos"

   [[libknet8.download]]
   sha256 = "c2546da8ae4f2ef87d7a239f85fe514306cec7d14fbe782e828f83d862bc2706"
   url = "https://github.com/denizyuret/Knet.jl/releases/download/v1.3.8/libknet8.x86_64-macos.tar.gz"

[[libknet8]]
arch = "powerpc64le"
git-tree-sha1 = "40478d85ecfa6b64bc54ca18e75e477cf15ddf3a"
os = "linux"

   [[libknet8.download]]
   sha256 = "a7f7e8783aaebae2d6379cfca340999de70bb202d776a05fba661d1c8626e7cc"
   url = "https://github.com/denizyuret/Knet.jl/releases/download/v1.4.3/libknet8.ppc64le-linux-gnu.tar.gz"
